apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: team-beta
  name: team-beta-role
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "list", "create", "delete"]
