apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alpha-user-binding
  namespace: team-alpha
subjects:
- kind: ServiceAccount
  name: alpha-user
  namespace: team-alpha
roleRef:
  kind: Role
  name: team-alpha-role
  apiGroup: rbac.authorization.k8s.io
