apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: beta-user-binding
  namespace: team-beta
subjects:
- kind: ServiceAccount
  name: beta-user
  namespace: team-beta
roleRef:
  kind: Role
  name: team-beta-role
  apiGroup: rbac.authorization.k8s.io
