name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  kubectl-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          # ensure the directory exists
          mkdir -p $HOME/.kube
          # decode your secret into the file
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config


      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f .

